name: Build and Publish web

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get npm cache directory
      id: npm-cache-dir
      run: |
        echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
    - name: Configure npm cache
      uses: actions/cache@v3
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Checkout modified web interface
      uses: actions/checkout@v3
      with:
        path: web

    - name: Store commit of web interface
      id: web-commit
      run: |
        cd web
        echo "commit=$(git log -1 --format='%H' | cut -c -10)" >> $GITHUB_OUTPUT
    - name: Build and copy web interface
      run: |
        cd web
        npm install
        cp -r dist ../docker/
        tar czf dist.tar.gz dist
    - name: Upload web interface
      uses: softprops/action-gh-release@v1
      with:
        tag_name: $(git describe --tags --abbrev=0)
        name: jellyfin-web-10.8.8+${{ steps.web-commit.outputs.commit }}.tar.gz
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
